2007-06-26  William Cohen  <wcohen@redhat.com>
	PR 4529
	* coveragedb.cxx: New.
	* coveragedb.h: New.
	* Makefile.am: Add coveragedb.cxx and sqlite3 to build.
	* Makefile.in: Regenerated.
	* configure.ac: Add test for sqlite3
	* configure: Regenerated.
	* systemtap.spec.in: Add dependencies for sqlite3/sqlite3-devel.
	* elaborate.h, elaborate.cxx
	  (derived_probe::collect_derivation_chain): New.
	  (alias_expansion_builder::build): Correct token location.
	  (semantic_pass_opt[12): Track used and unused variables/functions.
	* session.h (tapset_compile_coverage, unused_globals,
	  unused_probes, unused_functions): New fields.
	* staptree.h (unused_locals, probe_point::str): New member.
	* staptree.cxx: Ditto.
	* main.cxx: Add "-q" tapset coverage option and SYSTEMTAP_COVERAGE env.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6657,6 +6657,83 @@ fi
 { echo "$as_me:$LINENO: stap will link $stap_LIBS" >&5
 echo "$as_me: stap will link $stap_LIBS" >&6;}
 
+
+{ echo "$as_me:$LINENO: checking for sqlite3_open in -lsqlite3" >&5
+echo $ECHO_N "checking for sqlite3_open in -lsqlite3... $ECHO_C" >&6; }
+if test "${ac_cv_lib_sqlite3_sqlite3_open+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lsqlite3  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char sqlite3_open ();
+int
+main ()
+{
+return sqlite3_open ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_sqlite3_sqlite3_open=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_sqlite3_sqlite3_open=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_sqlite3_sqlite3_open" >&5
+echo "${ECHO_T}$ac_cv_lib_sqlite3_sqlite3_open" >&6; }
+if test $ac_cv_lib_sqlite3_sqlite3_open = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBSQLITE3 1
+_ACEOF
+
+  LIBS="-lsqlite3 $LIBS"
+
+else
+
+  { { echo "$as_me:$LINENO: error: missing sqlite development headers/libraries" >&5
+echo "$as_me: error: missing sqlite development headers/libraries" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
 date=`date +%Y-%m-%d`
 
 cat >>confdefs.h <<_ACEOF
