2007-03-17  Frank Ch. Eigler  <fche@elastic.org>
	* configure.ac: Tweak missing elfutils error message.
	* configure: Regenerated.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5866,8 +5866,8 @@ _ACEOF
 
 else
 
-    { { echo "$as_me:$LINENO: error: systemtap requires elfutils 0.123+" >&5
-echo "$as_me: error: systemtap requires elfutils 0.123+" >&2;}
+    { { echo "$as_me:$LINENO: error: missing elfutils development headers/libraries (dw 0.123+)" >&5
+echo "$as_me: error: missing elfutils development headers/libraries (dw 0.123+)" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -5945,8 +5945,8 @@ _ACEOF
 
 else
 
-    { { echo "$as_me:$LINENO: error: systemtap requires elfutils 0.123+" >&5
-echo "$as_me: error: systemtap requires elfutils 0.123+" >&2;}
+    { { echo "$as_me:$LINENO: error: missing elfutils development headers/libraries (ebl 0.123+)" >&5
+echo "$as_me: error: missing elfutils development headers/libraries (ebl 0.123+)" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
