2005-08-24  Frank Ch. Eigler  <fche@elastic.org>
	* configure.ac: Require elfutils 0.114.
	* tapsets.cxx: Brought back graydon's changes.
	* configure: Regenerated.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5075,9 +5075,9 @@ fi
 save_LIBS="$LIBS"
 
 
-echo "$as_me:$LINENO: checking for dwfl_begin in -ldw" >&5
-echo $ECHO_N "checking for dwfl_begin in -ldw... $ECHO_C" >&6
-if test "${ac_cv_lib_dw_dwfl_begin+set}" = set; then
+echo "$as_me:$LINENO: checking for dwarf_func_inline in -ldw" >&5
+echo $ECHO_N "checking for dwarf_func_inline in -ldw... $ECHO_C" >&6
+if test "${ac_cv_lib_dw_dwarf_func_inline+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
@@ -5095,11 +5095,11 @@ extern "C"
 #endif
 /* We use char because int might match the return type of a gcc2
    builtin and then its argument prototype would still apply.  */
-char dwfl_begin ();
+char dwarf_func_inline ();
 int
 main ()
 {
-dwfl_begin ();
+dwarf_func_inline ();
   ;
   return 0;
 }
@@ -5126,20 +5126,20 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_lib_dw_dwfl_begin=yes
+  ac_cv_lib_dw_dwarf_func_inline=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-ac_cv_lib_dw_dwfl_begin=no
+ac_cv_lib_dw_dwarf_func_inline=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_dw_dwfl_begin" >&5
-echo "${ECHO_T}$ac_cv_lib_dw_dwfl_begin" >&6
-if test $ac_cv_lib_dw_dwfl_begin = yes; then
+echo "$as_me:$LINENO: result: $ac_cv_lib_dw_dwarf_func_inline" >&5
+echo "${ECHO_T}$ac_cv_lib_dw_dwarf_func_inline" >&6
+if test $ac_cv_lib_dw_dwarf_func_inline = yes; then
   cat >>confdefs.h <<_ACEOF
 #define HAVE_LIBDW 1
 _ACEOF
@@ -5152,10 +5152,10 @@ stap_LIBS="$LIBS"
 LIBS="$SAVE_LIBS"
 
 
-if test $ac_cv_lib_dw_dwfl_begin != yes
+if test $ac_cv_lib_dw_dwarf_func_inline != yes
 then
-  { { echo "$as_me:$LINENO: error: systemtap requires elfutils 0.111+" >&5
-echo "$as_me: error: systemtap requires elfutils 0.111+" >&2;}
+  { { echo "$as_me:$LINENO: error: systemtap requires elfutils 0.114+" >&5
+echo "$as_me: error: systemtap requires elfutils 0.114+" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
