2005-09-06  Frank Ch. Eigler  <fche@elastic.org>
	* configure.ac: Require elfutils 0.115+.
	* tapsets.cxx: Restore graydon's PR 1244 code.
	* testsuite/buildok/eighteen.stp: Correct typing.
	* configure: Regenerated.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5075,9 +5075,9 @@ fi
 save_LIBS="$LIBS"
 
 
-echo "$as_me:$LINENO: checking for dwarf_func_inline in -ldw" >&5
-echo $ECHO_N "checking for dwarf_func_inline in -ldw... $ECHO_C" >&6
-if test "${ac_cv_lib_dw_dwarf_func_inline+set}" = set; then
+echo "$as_me:$LINENO: checking for dwarf_getscopes_die in -ldw" >&5
+echo $ECHO_N "checking for dwarf_getscopes_die in -ldw... $ECHO_C" >&6
+if test "${ac_cv_lib_dw_dwarf_getscopes_die+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
@@ -5095,11 +5095,11 @@ extern "C"
 #endif
 /* We use char because int might match the return type of a gcc2
    builtin and then its argument prototype would still apply.  */
-char dwarf_func_inline ();
+char dwarf_getscopes_die ();
 int
 main ()
 {
-dwarf_func_inline ();
+dwarf_getscopes_die ();
   ;
   return 0;
 }
@@ -5126,38 +5126,36 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_lib_dw_dwarf_func_inline=yes
+  ac_cv_lib_dw_dwarf_getscopes_die=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-ac_cv_lib_dw_dwarf_func_inline=no
+ac_cv_lib_dw_dwarf_getscopes_die=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_dw_dwarf_func_inline" >&5
-echo "${ECHO_T}$ac_cv_lib_dw_dwarf_func_inline" >&6
-if test $ac_cv_lib_dw_dwarf_func_inline = yes; then
+echo "$as_me:$LINENO: result: $ac_cv_lib_dw_dwarf_getscopes_die" >&5
+echo "${ECHO_T}$ac_cv_lib_dw_dwarf_getscopes_die" >&6
+if test $ac_cv_lib_dw_dwarf_getscopes_die = yes; then
   cat >>confdefs.h <<_ACEOF
 #define HAVE_LIBDW 1
 _ACEOF
 
   LIBS="-ldw $LIBS"
 
+else
+
+  { { echo "$as_me:$LINENO: error: systemtap requires elfutils 0.115+" >&5
+echo "$as_me: error: systemtap requires elfutils 0.115+" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 stap_LIBS="$LIBS"
 LIBS="$SAVE_LIBS"
 
-
-if test $ac_cv_lib_dw_dwarf_func_inline != yes
-then
-  { { echo "$as_me:$LINENO: error: systemtap requires elfutils 0.114+" >&5
-echo "$as_me: error: systemtap requires elfutils 0.114+" >&2;}
-   { (exit 1); exit 1; }; }
-fi
 
 date=`date +%Y-%m-%d`
 
