Check for xmlto that generates pdf.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6472,14 +6472,34 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
+if test "x${have_xmlto}" == "xyes"; then
+{ echo "$as_me:$LINENO: checking for xmlto pdf support" >&5
+echo $ECHO_N "checking for xmlto pdf support... $ECHO_C" >&6; }
+cat > conftest.$ac_ext << EOF
+<?xml version="1.0" encoding="UTF-8"?>
+<!DOCTYPE book PUBLIC "-//OASIS//DTD DocBook XML V4.1.2//EN"
+"http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd" >
+   <book id="pdffromxml">
+   </book>
+EOF
+   xmlto pdf conftest.$ac_ext >& /dev/null
+   if test $? == 0; then
+      have_xmlto_pdf="yes"
+      { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+   else
+      { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+   fi
+fi
 if test "$enable_refdocs" == "yes"; then
-   if test "x${have_xmlto}" != "xyes"; then
-      { { echo "$as_me:$LINENO: error: cannot find xmlto for building reference documentation" >&5
-echo "$as_me: error: cannot find xmlto for building reference documentation" >&2;}
+   if test "x${have_xmlto}${have_xmlto_pdf}" != "xyesyes"; then
+      { { echo "$as_me:$LINENO: error: cannot find proper yxmlto for building reference documentation" >&5
+echo "$as_me: error: cannot find proper yxmlto for building reference documentation" >&2;}
    { (exit 1); exit 1; }; }
    fi
 fi
-if test "x${have_xmlto}" == "xyes" -a "$enable_refdocs" != "no" -a "${building_docs}" == "yes"; then
+if test "x${have_xmlto}${have_xmlto_pdf}" == "xyesyes" -a "$enable_refdocs" != "no" -a "${building_docs}" == "yes"; then
    building_refdocs="yes"
 fi
  if test "$building_refdocs" == "yes"; then
