Ensure that a systemtap server is available if 'server' is specified in EXTRA_TOOL_OPTS for 'make check' and 'make installcheck'

diff --git a/stap-server b/stap-server
--- a/stap-server
+++ b/stap-server
@@ -13,6 +13,9 @@
 # contained in the unpacked tree to build the requested systemtap kernel module.
 # This module is then written to stdout.
 
+# Catch ctrl-c and other termination signals
+trap 'terminate' SIGTERM SIGINT
+
 #-----------------------------------------------------------------------------
 # Helper functions.
 #-----------------------------------------------------------------------------
@@ -312,6 +315,7 @@ function call_stap {
     else
 	server_p_phase=$p_phase
     fi
+
     eval stap $cmdline -k -p $server_p_phase \
 	>>  $tmpdir_server/stdout \
 	2>> $tmpdir_server/stderr
@@ -328,19 +332,21 @@ function create_response {
     tmpdir_line=`cat stderr | grep "Keeping temp"`
     tmpdir_stap=`expr "$tmpdir_line" : '.*"\(.*\)".*'`
 
-    # Remove the message about keeping th<e stap temp directory from stderr, unless
+    # Remove the message about keeping the stap temp directory from stderr, unless
     # the user did request to keep it.
-    if test $keep_temps != 1; then
-	sed -i "/^Keeping temp/d" stderr
+    if test "X$tmpdir_stap" != "X"; then
+	if test $keep_temps != 1; then
+	    sed -i "/^Keeping temp/d" stderr
+	fi
+
+        # Add the contents of the stap temp directory to the server output directory
+	ln -s $tmpdir_stap `basename $tmpdir_stap`
     fi
 
     # If the user specified -p5, remove the name of the kernel module from stdout.
     if test $p_phase = 5; then
 	sed -i '/\.ko$/d' stdout
     fi
-
-    # Add the contents of the stap temp directory to the server output directory
-    ln -s $tmpdir_stap `basename $tmpdir_stap`
 }
 
 # function: package_response
@@ -402,6 +408,15 @@ function cleanup {
 	rm -fr $tmpdir_server
 	rm -fr $tmpdir_stap
     fi
+}
+
+# function: terminate
+#
+# Terminate gracefully.
+function terminate {
+    # Clean up
+    cleanup
+    exit
 }
 
 #-----------------------------------------------------------------------------
diff --git a/stap-serverd b/stap-serverd
--- a/stap-serverd
+++ b/stap-serverd
@@ -13,8 +13,8 @@
 # incoming connections. When a connection is detected, the stap-server script
 # is run to handle the request.
 
-# Catch ctrl-c
-trap 'handle_sigint' SIGINT
+# Catch ctrl-c and other termination signals
+trap 'terminate' SIGTERM SIGINT
 
 #-----------------------------------------------------------------------------
 # Helper functions.
@@ -61,7 +61,10 @@ function listen {
     # Loop forever accepting requests
     while true
     do
-	nc -l $port < $fifo_name | stap-server $((port + 1)) > $fifo_name 2>&1
+	# Run this in the background and wait for it. This way any signals
+	# received (i.e. SIGTERM) will be processed.
+	nc -l $port < $fifo_name | stap-server $((port + 1)) > $fifo_name 2>&1 &
+	wait %nc
     done
 }
 
@@ -74,13 +77,24 @@ function fatal {
     exit 1
 }
 
-# function: handle_sigint
+# function: terminate
 #
-# Terminate gracefully when SIGINT is received.
-function handle_sigint {
-    echo "$0: received SIGINT. Exiting."
+# Terminate gracefully.
+function terminate {
+    echo "$0: Exiting"
+
+    # Kill the running 'avahi-publish-service' job
+    kill -s SIGTERM %avahi-publish-service 2> /dev/null
+    wait %avahi-publish-service 2> /dev/null
+
+    # Kill any running 'nc -l' job.
+    kill -s SIGTERM "%nc -l" 2> /dev/null
+    wait "%nc - l" 2> /dev/null
+
+    # Clean up
     cd `dirname $tmpdir`
     rm -fr $tmpdir
+
     exit
 }
 
