stap-serverd was incorectly determining that the server could not be started.

diff --git a/stap-serverd b/stap-serverd
--- a/stap-serverd
+++ b/stap-serverd
@@ -65,21 +65,31 @@ function listen {
 
     # Loop forever accepting requests
     first=1
+    set -o pipefail # We want the status of 'nc' not 'stap-server'.
     while true
     do
 	# Run this in the background and wait for it. This way any signals
 	# received (i.e. SIGTERM) will be processed. Make sure we don't
 	# advertise our presence until we're actually listening.
-	nc -l $port < $fifo_name | stap-server $((port + 1)) > $fifo_name 2>&1 &
-	if test $first = 1; then
-	    advertise_presence
-	    first=0
+	for ((attempt=0; $attempt < 5; ++attempt))
+	do
+	    nc -l $port < $fifo_name | stap-server $((port + 1)) > $fifo_name 2>&1 &
+	    if test $first = 1; then
+		advertise_presence
+		first=0
+	    fi
+	    wait %nc
+	    rc=$?
+            if test $rc = 127 -o $rc = 0; then
+		break; # success
+            fi
+	    sleep 1
+	done
+	if test $attempt = 10; then
+	    fatal "ERROR: cannot listen on port $port. rc==$rc"
 	fi
-	wait %nc
-        if [ $? -ne 0 ]; then
-            fatal "ERROR: cannot listen on port $port"
-        fi
     done
+    set +o pipefail # restore
 }
 
 # function: fatal [ MESSAGE ]
@@ -88,6 +98,7 @@ function listen {
 # Prints its arguments to stderr and exits
 function fatal {
     echo "$@" >&2
+    terminate
     exit 1
 }
 
