PR 12101: stap-server should use proper cert passwords
Step 1: The server's certificate database now uses no password by default
        (useful for full automation).
        Preliminary support for password prompting for databases created
        with a password.

diff --git a/stap-gen-cert b/stap-gen-cert
--- a/stap-gen-cert
+++ b/stap-gen-cert
@@ -3,7 +3,7 @@
 # Generate a certificate for the systemtap server and add it to the
 # database of trusted servers for the client.
 #
-# Copyright (C) 2008-2010 Red Hat Inc.
+# Copyright (C) 2008-2011 Red Hat Inc.
 #
 # This file is part of systemtap, and is free software.  You can
 # redistribute it and/or modify it under the terms of the GNU General
@@ -13,17 +13,32 @@
 # Initialize the environment
 . ${PKGLIBEXECDIR}stap-env
 
-# Arguments
-serverdb="$1"
-shift
-
-# Domains for the certificate.
+serverdb=
 domains="$HOSTNAME"
+use_db_password=0
+
+# Arguments
 while test $# != 0
 do
-    test -n "$domains" && domains="$domains,"
-    domains="${domains}$1"
-    shift
+  case "$1" in
+    -P)
+      use_db_password=1
+      shift 1
+      ;;
+    --)
+      ;;
+    *)
+      if test -z "$serverdb"; then
+        # Server cert database
+	serverdb="$1"
+      else
+        # Domains for the certificate.
+        test -n "$domains" && domains="$domains,"
+        domains="${domains}$1"
+      fi
+      ;;
+  esac
+  shift
 done
 
 # Obtain the certificate database directory name.
@@ -38,20 +53,25 @@ if ! mkdir -p -m 755 "$serverdb"; then
     exit 1
 fi
 
-# Create the certificate database password file. Care must be taken
-# that this file is only readable by the owner.
-if ! (touch "$serverdb/pw" && chmod 600 "$serverdb/pw"); then
-    echo "Unable to create the server certificate database password file: $serverdb/pw" >&2
+# If not using a database password, then create an empty certificate database password
+# file. This is a temporary file used only because certutil demands it.
+if test $use_db_password = 0; then
+  if ! (touch "$serverdb/pw" && chmod 600 "$serverdb/pw"); then
+    echo "Unable to create temporary certificate database password file: $serverdb/pw" >&2
     exit 1
+  fi
+  # Generate the server certificate database. Filter the message about the passowrd file
+  # being empty.
+  certutil -N -d "$serverdb" -f "$serverdb/pw" 2>&1 >/dev/null | \
+    sed '/password file contains no data/ d'
+else
+  # Generate the server certificate database. certutil will ask for the password.
+  certutil -N -d "$serverdb" >/dev/null
 fi
+rc=$?
+rm -fr "$serverdb/pw"
 
-# Generate a random password.
-mkpasswd -l 20 > "$serverdb/pw" 2>/dev/null || \
-apg -a 1 -n 1 -m 20 -x 20 > "$serverdb/pw" 2>/dev/null || \
-(read -n20 password </dev/urandom; echo "$password" > "$serverdb/pw")
-
-# Generate the server certificate database
-if ! certutil -N -d "$serverdb" -f "$serverdb/pw" > /dev/null; then
+if test $rc != 0; then
     echo "Unable to initialize the server certificate database directory: $serverdb" >&2
     exit 1
 fi
@@ -60,7 +80,7 @@ fi
 dd bs=123 count=1 < /dev/urandom > "$serverdb/noise" 2> /dev/null
 
 # Generate a request for the server's certificate.
-certutil -R -d "$serverdb" -f "$serverdb/pw" -s "CN=Systemtap Compile Server, OU=Systemtap" \
+certutil -R -d "$serverdb" -s "CN=Systemtap Compile Server, OU=Systemtap" \
          -o "$serverdb/stap.req" -z "$serverdb/noise" 2> /dev/null
 rm -fr "$serverdb/noise"
 
@@ -72,7 +92,7 @@ fi
 
 # Now generate the actual certificate. Make it valid for 1 year.
 certutil -C -i "$serverdb/stap.req" -o "$serverdb/$stap_certfile" -x -d "$serverdb" \
-         -f "$serverdb/pw" -v 12 -5 -8 "$domains" >/dev/null <<-EOF
+         -v 12 -5 -8 "$domains" >/dev/null <<-EOF
 1
 3
 7
@@ -82,7 +102,7 @@ EOF
 rm -fr "$serverdb/stap.req"
 
 # Add the certificate to the server's certificate/key database as a trusted peer, ssl server and object signer
-certutil -A -n stap-server -t "PCu,,PCu" -i "$serverdb/$stap_certfile" -d "$serverdb" -f "$serverdb/pw"
+certutil -A -n stap-server -t "PCu,,PCu" -i "$serverdb/$stap_certfile" -d "$serverdb"
 
 # Print some information about the certificate.
 echo "Certificate $serverdb/$stap_certfile created and added to database $serverdb"
