Ensure that the client cert database and server cert are readable by all.

diff --git a/stap-add-server-cert b/stap-add-server-cert
--- a/stap-add-server-cert
+++ b/stap-add-server-cert
@@ -40,9 +40,7 @@ fi
 
 # Ensure that the database is readable by others
 if ! chmod +r $2/*.db; then
-    echo "Unable to make the client certificate database $2 readable by others" >&2
-    exit 1
+    echo "Warning: unable to make the client certificate database $2 readable by others" >&2
 fi
-    
 
 exit 0
diff --git a/stap-gen-server-cert b/stap-gen-server-cert
--- a/stap-gen-server-cert
+++ b/stap-gen-server-cert
@@ -83,6 +83,11 @@ y
 EOF
 rm -fr $1/stap-server.req
 
+# Ensure that the certificate is readable by others.
+if ! chmod +r $serverdb/stap-server.cert; then
+    echo "Warning: unable to make the server's certificate $serverdb/stap-server.cert readable by others" >&2
+fi
+
 # Add the certificate to the server's certificate/key database as a trusted peer, ssl server and object signer
 certutil -A -n stap-server -t "PCu,,PCu" -i $serverdb/stap-server.cert -d $serverdb -f $serverdb/pw
 
