Keep the user's stap certificate in stap.cert (was stap-server.cert). Rename the old cert file to the new name when it is encountered.

diff --git a/stap-gen-cert b/stap-gen-cert
--- a/stap-gen-cert
+++ b/stap-gen-cert
@@ -72,24 +72,24 @@ fi
 dd bs=123 count=1 < /dev/urandom > $serverdb/noise 2> /dev/null
 
 # Generate a request for the server's certificate.
-certutil -R -d $serverdb -f $serverdb/pw -s "CN=Systemtap Compile Server, OU=Systemtap, O=Red Hat, C=US" -o $serverdb/stap-server.req -z $serverdb/noise 2> /dev/null
+certutil -R -d $serverdb -f $serverdb/pw -s "CN=Systemtap Compile Server, OU=Systemtap, O=Red Hat, C=US" -o $serverdb/stap.req -z $serverdb/noise 2> /dev/null
 rm -fr $serverdb/noise
 
 # Create the certificate file first so that it always has the proper access permissions.
-if ! (touch $serverdb/stap-server.cert && chmod 644 $serverdb/stap-server.cert); then
-    echo "Unable to create the server certificate file: $serverdb/stap-server.cert" >&2
+if ! (touch $serverdb/$stap_certfile && chmod 644 $serverdb/$stap_certfile); then
+    echo "Unable to create the server certificate file: $serverdb/$stap_certfile" >&2
     exit 1
 fi
 
 # Now generate the actual certificate.
-certutil -C -i $serverdb/stap-server.req -o $serverdb/stap-server.cert -x -d $serverdb -f $serverdb/pw -5 -8 "$HOSTNAME,localhost" >/dev/null <<-EOF
+certutil -C -i $serverdb/stap.req -o $serverdb/$stap_certfile -x -d $serverdb -f $serverdb/pw -5 -8 "$HOSTNAME,localhost" >/dev/null <<-EOF
 1
 3
 7
 8
 y
 EOF
-rm -fr $serverdb/stap-server.req
+rm -fr $serverdb/stap.req
 
 # Add the certificate to the server's certificate/key database as a trusted peer, ssl server and object signer
-certutil -A -n stap-server -t "PCu,,PCu" -i $serverdb/stap-server.cert -d $serverdb -f $serverdb/pw
+certutil -A -n stap-server -t "PCu,,PCu" -i $serverdb/$stap_certfile -d $serverdb -f $serverdb/pw
